language: node_js
dist: trusty
addons:
  chrome: stable
  sauce_connect:
    username: mipengine
  jwt:
    secure: fKX9l/DmJZXzC0j7KzdZVdUiX+C4TP1XsE9CjJiCANiCFPGG4mCNgeGyTd77acmzc4U8XR0yEwlpM0MPMba9tftogd+V4vRflxQde09c823DUTytiuYfhH7iEwKuM9e2R7hmDNvZGV2g6DHLAJ0STff8JVBr9uTleLnTIRuUpNcGSJVs9U6xF7hz77YqbH5JE+WiAarVRBeVtXNrMLzqzfHRfCQT8XsZbl1vJeo7Ps+tBg1vty5Y+CQ4Hre5V0oRcIlrzNZp0/LiMTZ0hdnWZfV3O3EHtSon1Ih8Gqs/PN/l4/WmwfHyNWnuzWa2oYEJICEp9pY+XYc0EI3FXnhJ6dgYBU6osQ+ljgxeNT6Z9m/3KZst98r3WFYoAqgpe/XmLrLdBb7TXwgekyQGpu3lmFfixrlyWkMWIYzzkSepahKPnzDK1JqszmnvTN5IAt6pcRfolrZ/uaH9bY7oL3WjCt1l/pJIYwyFY0YkU/ph90OTDhPTOeqVWvnsDzT5gPJlA6wHDFTfXnyYIJPALMHM+lH0gegMu3EgF1hWNPF5oXbyyTurQSnaD0GFLcpzkGhWt+zrQnqLi2JSQcr3f8mRwhmFWe8RuQmEPFmMlKnkltSiZpNARXdzKwZ2SpA1VLzqYamQsfv/4B9nguI+ueAWC3fJb3PRbuJMzKFPACdQqnk=
node_js:
  - "5"
before_script:
  - npm install
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run test
  - npm run test:sl
  - npm run test:co
