language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
  - "5"
before_script:
  - npm install
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run test
  - npm run test:sl
  - npm run test:co
env:
  global:
    - SAUCE_USERNAME=mipengine
    - SAUCE_ACCESS_KEY=ba27a272-212b-4680-a047-4d8aefbe3084
